const mongoose = require("mongoose");
const productSchema = new mongoose.Schema({

    brandname:{
        type:String,
        required:true
    },
    productname:{
        type:String,
        required:true
    },
    catname:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true,
    },
    offprice:{
        type:Number,
        required:false,
    },
    productOffer:{
        type:String,
        required:false,
    },
    categoryOffer:{
        type:String,
        required:false,
    },
    image:{
        type:Array,
        required:true
    },
    stock:{
        type:Number,
        required:true
    },
    is_active:{
        type:Number,
        required:true,
        default:1
    },
    caseDiameter:{
        type:String,
        required:false
    },
    bandColour:{
        type:String,
        required:false
    },
    bandMaterial:{
        type:String,
        required:false
    },
    warranty:{
        type:String,
        required:false
    },
    movement:{
        type:String,
        required:false
    },
    weight:{
        type:String,
        required:false
    },
    country:{
        type:String,
        required:false,
    }

});

module.exports = mongoose.model('Product',productSchema);